server:
  port: 8083
spring:
  datasource:
   url: jdbc:mysql://localhost:3306/${MYSQL_DATABASE}?verifyServerCertificate=false&useSSL=false&requireSSL=false
   username: ${MYSQL_USER}
   password: ${MYSQL_PASSWORD}
#    url: jdbc:mysql://localhost:3306/Step7?verifyServerCertificate=false&useSSL=false&requireSSL=false
#    username: root
#    password: pass@word1
  jpa:
    hibernate:
      ddl-auto: update
      
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect